/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package asn6.view;

import asn6.pkg.Mobil;
import asn6.pkg.blueprint.Mesin;
import asn6.utils.Database;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ibnumardini
 */
public class VehicleFrame extends javax.swing.JFrame {

    DefaultTableModel model;

    /**
     * Creates new form VehicleFrame
     */
    public VehicleFrame() {
        initComponents();
        model = (DefaultTableModel) tblVehicles.getModel();

        loadData();
    }

    private void loadData() {
        model.setRowCount(0);

        try {
            Connection link = Database.getConnection();

            Statement statement = link.createStatement();

            String query = "SELECT number_of_cylinders, cylinder_capacity, fuel, number_of_seat FROM mobil";

            ResultSet chunk = statement.executeQuery(query);

            while (chunk.next()) {
                int numberOfCylinders = chunk.getInt("number_of_cylinders");
                int cylinderCapacity = chunk.getInt("cylinder_capacity");
                String fuel = chunk.getString("fuel");
                int numberOfSeat = chunk.getInt("number_of_seat");

                Mesin engine = new Mesin(numberOfCylinders, cylinderCapacity);
                Mobil car = new Mobil(fuel, engine, numberOfSeat);

                Object[] data = {
                    car.getEngine().numberOfCylinders,
                    car.getEngine().cylinderCapacity,
                    car.getFuel(),
                    car.getNumberOfSeat()
                };

                model.addRow(data);
            }

        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pTblVehicles = new javax.swing.JScrollPane();
        tblVehicles = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lblNumberOfCylinders = new javax.swing.JLabel();
        iNumberOfCylinders = new javax.swing.JTextField();
        lblCylinderCapacity = new javax.swing.JLabel();
        iCylinderCapacity = new javax.swing.JTextField();
        iFuel = new javax.swing.JTextField();
        lblFuel = new javax.swing.JLabel();
        iNumberOfSeat = new javax.swing.JTextField();
        lblNumberOfSeat = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setFont(new java.awt.Font("Inter", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APLIKASI MANAJEMEN KENDARAAN");

        jLabel6.setText("by Muhammad Fatkurozi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(jLabel1))
                .addGap(162, 162, 162))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jumlah Silinder", "Kapasitas Silinder", "Bahan Bakar", "Jumlah Kursi"
            }
        ));
        tblVehicles.getTableHeader().setReorderingAllowed(false);
        pTblVehicles.setViewportView(tblVehicles);

        lblNumberOfCylinders.setText("Jumlah Silinder");

        lblCylinderCapacity.setText("Kapasitas Silinder");

        lblFuel.setText("Bahan Bakar");

        lblNumberOfSeat.setText("Jumlah Kursi");

        btnAdd.setBackground(new java.awt.Color(153, 204, 255));
        btnAdd.setForeground(new java.awt.Color(51, 51, 51));
        btnAdd.setText("Tambah");
        btnAdd.setBorderPainted(false);
        btnAdd.setFocusPainted(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAdd)
                    .addComponent(lblCylinderCapacity)
                    .addComponent(lblNumberOfCylinders)
                    .addComponent(lblFuel)
                    .addComponent(lblNumberOfSeat))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(iFuel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(iCylinderCapacity, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iNumberOfCylinders, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iNumberOfSeat))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumberOfCylinders)
                    .addComponent(iNumberOfCylinders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCylinderCapacity)
                    .addComponent(iCylinderCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFuel)
                    .addComponent(iFuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumberOfSeat)
                    .addComponent(iNumberOfSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pTblVehicles, javax.swing.GroupLayout.DEFAULT_SIZE, 765, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(pTblVehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String inputNumberOfCylinders = iNumberOfCylinders.getText();
        String inputCylinderCapacity = iCylinderCapacity.getText();
        String fuel = iFuel.getText();
        String inputNumberOfSeat = iNumberOfSeat.getText();

        if (inputNumberOfCylinders.isBlank() || inputCylinderCapacity.isBlank() || fuel.isBlank() || inputNumberOfSeat.isBlank()) {
            JOptionPane.showMessageDialog(null, "Gagal menambah data, ada yang kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int numberOfCylinders = Integer.parseInt(inputNumberOfCylinders);
            int cylinderCapacity = Integer.parseInt(inputCylinderCapacity);
            int numberOfSeat = Integer.parseInt(inputNumberOfSeat);

            Mesin engine = new Mesin(numberOfCylinders, cylinderCapacity);
            Mobil car = new Mobil(fuel, engine, numberOfSeat);

            Connection link = Database.getConnection();

            String query = "INSERT INTO mobil(number_of_cylinders, cylinder_capacity, fuel, number_of_seat) VALUES(?, ?, ?, ?)";

            PreparedStatement statement = link.prepareStatement(query);

            statement.setInt(1, car.getEngine().numberOfCylinders);
            statement.setInt(2, car.getEngine().cylinderCapacity);
            statement.setString(3, car.getFuel());
            statement.setInt(4, car.getNumberOfSeat());

            statement.execute();

            iNumberOfCylinders.setText("");
            iCylinderCapacity.setText("");
            iFuel.setText("");
            iNumberOfSeat.setText("");

            loadData();

            JOptionPane.showMessageDialog(null, "Berhasil menambah data!");
        } catch (NumberFormatException | SQLException e) {
            System.out.println(e);

            JOptionPane.showMessageDialog(null, "Gagal menambah data!, " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VehicleFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JTextField iCylinderCapacity;
    private javax.swing.JTextField iFuel;
    private javax.swing.JTextField iNumberOfCylinders;
    private javax.swing.JTextField iNumberOfSeat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCylinderCapacity;
    private javax.swing.JLabel lblFuel;
    private javax.swing.JLabel lblNumberOfCylinders;
    private javax.swing.JLabel lblNumberOfSeat;
    private javax.swing.JScrollPane pTblVehicles;
    private javax.swing.JTable tblVehicles;
    // End of variables declaration//GEN-END:variables
}
